INSERT INTO product (name) VALUES ('Телевизор');
INSERT INTO product (name) VALUES ('Смартфон');
INSERT INTO product (name) VALUES ('Соковыжималка');
INSERT INTO product (name) VALUES ('Наушники');
INSERT INTO product (name) VALUES ('Клавиатура');
INSERT INTO buyer (name, lastname, age) VALUES ('Олег', 'Попов', 18);
INSERT INTO buyer (name, lastname, age) VALUES ('Сергей', 'Васильев', 20);
INSERT INTO buyer (name, lastname, age) VALUES ('Елена', 'Петрова', 18);
INSERT INTO buyer (name, lastname, age) VALUES ('Наталья', 'Соколова', 45);
INSERT INTO buyer (name, lastname, age) VALUES ('Николай', 'Михайлов', 50);
INSERT INTO purchase (buyer_id, product_id, count, amount, date) VALUES (2, 4, 1, 10.55, '2022.07.21');
INSERT INTO purchase (buyer_id, product_id, count, amount, date) VALUES (2, 1, 3, 800.63, '2022.07.15');
INSERT INTO purchase (buyer_id, product_id, count, amount, date) VALUES (3, 4, 1, 10.55, '2022.07.14');
INSERT INTO purchase (buyer_id, product_id, count, amount, date) VALUES (3, 5, 5, 90.75, '2022.06.20');
INSERT INTO purchase (buyer_id, product_id, count, amount, date) VALUES (4, 5, 1, 18.15, '2022.06.18');
INSERT INTO purchase (buyer_id, product_id, count, amount, date) VALUES (5, 5, 1, 18.15, '2022.06.10');
INSERT INTO purchase (buyer_id, product_id, count, amount, date) VALUES (1, 2, 5, 1002.80, '2021.01.01');
INSERT INTO purchase (buyer_id, product_id, count, amount, date) VALUES (1, 2, 5, 1002.80, '2021.01.01');
